PriceList_Changes
VIENNA-Advantage-ERP-CRM/official-VAFramework-ERP-CRM pull request #749
Opened 2021-02-01 04:24 UTC by kumarp-v

Price List - Valid From date changes

2021-02-02 05:29 UTC, Manjot-Vienna commented on VIS/Areas/VIS/Models/Callouts/MPriceListVersionModel.cs
> +
Please do commenting on functions and changes you did

2021-02-02 05:29 UTC, Manjot-Vienna requested changes
Please do commenting

2021-02-02 13:15 UTC, Manjot-Vienna submitted a review, later dismissed
OK

2021-02-02 13:22 UTC, Manjot-Vienna commented on VIS/Areas/VIS/Models/Callouts/MPriceListVersionModel.cs
> +        /// <param name="transactionType"></param>
add parameter names and what that method will return Return

2021-02-02 13:23 UTC, Manjot-Vienna commented on VIS/Areas/VIS/Models/Callouts/MPriceListVersionModel.cs
> +        /// <param name="transactionId"></param>
same in this function as well

2021-02-03 06:47 UTC, Manjot-Vienna approved these changes
OK

2021-02-03 06:52 UTC, Amit-Vienna approved these changes
ok

2021-02-03 06:52 UTC, merged