Pricelist - QA change : handling inactive records
VIENNA-Advantage-ERP-CRM/official-VAFramework-ERP-CRM pull request #764
Opened 2021-02-12 13:42 UTC by kumarp-v

2021-02-23 06:05 UTC, Manjot-Vienna commented on VIS/Areas/VIS/Models/Callouts/MPriceListVersionModel.cs
> -            if (Util.GetValueOfInt(transactionId) > 0)
Commenting is missing

2021-02-23 06:19 UTC, Manjot-Vienna commented on VIS/Areas/VIS/Models/Callouts/MPriceListVersionModel.cs
> +                    {
Commenting is missing

2021-02-26 05:27 UTC, Amit-Vienna commented on VIS/Areas/VIS/Models/Callouts/MProductPricingModel.cs
> +                sbparams.Append(",").Append(Util.GetValueOfString(Convert.ToDateTime(orderDate).ToString("MM-dd-yyyy")));
not required Util.GetValueOfString

2021-02-26 05:30 UTC, Amit-Vienna commented on ModelLibrary/Model/MProductPricing.cs
> +                    if (_C_UOM_ID <= UOM_EACH)
no need UOM_EACH variable, when _C_UOM_ID = 0 then  execute this section

2021-02-26 05:31 UTC, Amit-Vienna requested changes
change the requested

2021-02-26 07:33 UTC, Manjot-Vienna approved these changes
Now it's OK

2021-02-26 07:50 UTC, Amit-Vienna approved these changes
ok

2021-02-26 07:50 UTC, merged